Rebu/config/routes.rb
Rails.application.routes.draw do
  resources :rides
  devise_for :users
  get 'home/index'

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

Rebu/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Rebu/app/models/ride.rb
class Ride < ApplicationRecord
  belongs_to :user
end

Rebu/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

Rebu/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Rebu/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

Rebu/app/controllers/rides_controller.rb
class RidesController < ApplicationController
  before_action :set_ride, only: [:show, :edit, :update, :destroy]

  # GET /rides
  # GET /rides.json
  def index
    @rides = Ride.all
  end

  # GET /rides/1
  # GET /rides/1.json
  def show
  end

  # GET /rides/new
  def new
    @ride = Ride.new
  end

  # GET /rides/1/edit
  def edit
  end

  # POST /rides
  # POST /rides.json
  def create
    @ride = Ride.new(ride_params)

    respond_to do |format|
      if @ride.save
        format.html { redirect_to @ride, notice: 'Ride was successfully created.' }
        format.json { render :show, status: :created, location: @ride }
      else
        format.html { render :new }
        format.json { render json: @ride.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rides/1
  # PATCH/PUT /rides/1.json
  def update
    respond_to do |format|
      if @ride.update(ride_params)
        format.html { redirect_to @ride, notice: 'Ride was successfully updated.' }
        format.json { render :show, status: :ok, location: @ride }
      else
        format.html { render :edit }
        format.json { render json: @ride.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rides/1
  # DELETE /rides/1.json
  def destroy
    @ride.destroy
    respond_to do |format|
      format.html { redirect_to rides_url, notice: 'Ride was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ride
      @ride = Ride.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ride_params
      params.require(:ride).permit(:origin, :destination, :weekday, :time, :price, :note, :user_id)
    end
end

Rebu/app/helpers/application_helper.rb
module ApplicationHelper
end

Rebu/app/helpers/home_helper.rb
module HomeHelper
end

Rebu/app/helpers/rides_helper.rb
module RidesHelper
end

Rebu/app/views/home/index.html.erb
<%= render partial: "shared/cabecalho" %>

<ul>
	<li>
</ul>

<%= render partial: "shared/rodape" %>

Rebu/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rebu</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Rebu/app/views/rides/_form.html.erb
<%= form_with(model: ride, local: true) do |form| %>
  <% if ride.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ride.errors.count, "error") %> prohibited this ride from being saved:</h2>

      <ul>
      <% ride.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :origin %>
    <%= form.text_field :origin %>
  </div>

  <div class="field">
    <%= form.label :destination %>
    <%= form.text_field :destination %>
  </div>

  <div class="field">
    <%= form.label :weekday %>
    <%= form.text_field :weekday %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.text_field :time %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :note %>
    <%= form.text_area :note %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Rebu/app/views/rides/edit.html.erb
<h1>Editing Ride</h1>

<%= render 'form', ride: @ride %>

<%= link_to 'Show', @ride %> |
<%= link_to 'Back', rides_path %>

Rebu/app/views/rides/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rides</h1>

<table>
  <thead>
    <tr>
      <th>Origin</th>
      <th>Destination</th>
      <th>Weekday</th>
      <th>Time</th>
      <th>Price</th>
      <th>Note</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rides.each do |ride| %>
      <tr>
        <td><%= ride.origin %></td>
        <td><%= ride.destination %></td>
        <td><%= ride.weekday %></td>
        <td><%= ride.time %></td>
        <td><%= ride.price %></td>
        <td><%= ride.note %></td>
        <td><%= ride.user %></td>
        <td><%= link_to 'Show', ride %></td>
        <td><%= link_to 'Edit', edit_ride_path(ride) %></td>
        <td><%= link_to 'Destroy', ride, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ride', new_ride_path %>

Rebu/app/views/rides/new.html.erb
<h1>New Ride</h1>

<%= render 'form', ride: @ride %>

<%= link_to 'Back', rides_path %>

Rebu/app/views/rides/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Origin:</strong>
  <%= @ride.origin %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @ride.destination %>
</p>

<p>
  <strong>Weekday:</strong>
  <%= @ride.weekday %>
</p>

<p>
  <strong>Time:</strong>
  <%= @ride.time %>
</p>

<p>
  <strong>Price:</strong>
  <%= @ride.price %>
</p>

<p>
  <strong>Note:</strong>
  <%= @ride.note %>
</p>

<p>
  <strong>User:</strong>
  <%= @ride.user %>
</p>

<%= link_to 'Edit', edit_ride_path(@ride) %> |
<%= link_to 'Back', rides_path %>

Rebu/app/views/shared/_cabecalho.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<div class="container">
		<a href="../home/index" class="navbar-brand">Rebu</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSite">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarSite">
			<ul class="navbar-nav">
				<li class="nav-item"><a class="nav-link" href="../home/index">Inicio</a></li>
			<% if user_signed_in? %>
				<%= link_to 'Editar perfil', edit_user_registration_path, :class => 'nav-link' %>
				<li class="nav-item"><a class="nav-link" href="#">Nova Carona</a></li>
				<li class="nav-item"><a class="nav-link" href="#">Minhas caronas</a></li>
				<li class="nav-item"><%= link_to "Sair", destroy_user_session_path, method: :delete, :class => 'nav-link'%></li>
			 	<strong class="nav-link">Conta: <%= current_user.email %></strong>
			<% else %>
				<li class="nav-item"><a class="nav-link" href="/users/sign_in">Log In</a></li>
				<%= link_to "Registrar-se", new_user_registration_path, :class => 'nav-link' %> 
			</ul>
			<% end %>
		</div>
	</div>

  <form class="form-inline">
    <input class="form-control mr-sm-2" type="search" placeholder="Pesquisar" aria-label="Pesquisar">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Ok</button>
  </form>
</nav>